name: PoC App Robot on BrowserStack

on:
  workflow_dispatch:
    inputs:
      apk_path:
        description: "Caminho da APK no repo"
        required: true
        default: "app/app.apk"

jobs:
  run-tests:
    runs-on: ubuntu-latest
    env:
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps (Robot + AppiumLibrary)
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install robotframework robotframework-appiumlibrary
          fi

      - name: Upload APK to BrowserStack
        id: upload
        env:
          APK_PATH: ${{ inputs.apk_path }}
        run: |
          FILE_PATH="${{ github.workspace }}/${APK_PATH}"

          if [ ! -f "$FILE_PATH" ]; then
            echo "ERRO: APK não encontrada em: $FILE_PATH"
            exit 1
          fi

          echo "Fazendo upload da APK: $FILE_PATH"
          RESP=$(curl -s -u "$BROWSERSTACK_USERNAME:$BROWSERSTACK_ACCESS_KEY" \
            -X POST "https://api-cloud.browserstack.com/app-automate/upload" \
            -F "file=@${FILE_PATH}")

          echo "Response: $RESP"

          APP_URL=$(python - <<'PY'
                import json, os, sys
                data = json.loads(os.environ["RESP"])
                print(data["app_url"])
                PY
                        )

                        echo "APP_URL=$APP_URL" >> $GITHUB_ENV
                        echo "app_url=$APP_URL" >> $GITHUB_OUTPUT

                    - name: Run Robot tests
                        env:
                        APP_URL: ${{ env.APP_URL }}
                        run: |
                        mkdir -p results
                        echo "Usando APP_URL: $APP_URL"
                        robot -d results -v BS_APP:"$APP_URL" tests/mobile/mobile_example.robot

                    - name: Publicar relatórios do Robot
                        uses: actions/upload-artifact@v4
                        with:
                        name: robot-results
                        path: results/
