name: Accessibility Tests

on:
  workflow_dispatch:

jobs:
  accessibility-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          pip install robotframework
          pip install robotframework-seleniumlibrary
          pip install robotframework-axe
          sudo apt-get install -y chromium-browser

      - name: Run Accessibility Tests
        run: |
          robot -d results tests/accessibility_tests/

      - name: Upload Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: accessibility-test-results
          path: results/
