name: CI — API & Mobile (Robot Framework)

on:
  pull_request:
    branches: ["**"]
  push:
    branches: ["main"]
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:
    inputs:
      ref:
        description: "Branch ou tag a executar (ex.: develop, feature/minha-branch)"
        required: false
        default: ""

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

env:
  PYTHON_VERSION: "3.11"
  RESULTS_DIR: "results"
  RF_TAGS: ${{ github.event_name == 'pull_request' && 'smoke' || 'regression' }}

jobs:
  api:
    name: API
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref != '' && inputs.ref || github.ref }}
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: pip
          cache-dependency-path: requirements.txt
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Executar testes de API
        run: |
          mkdir -p "${RESULTS_DIR}/api"
          PATHS=""
          if compgen -G "tests/api/*.robot" > /dev/null; then
            PATHS="${PATHS} tests/api"
          fi
          if compgen -G "tests/API_tests/*.robot" > /dev/null; then
            PATHS="${PATHS} tests/API_tests"
          fi
          if [ -n "${PATHS}" ]; then
            robot -d "${RESULTS_DIR}/api" -i api ${PATHS}
          else
            echo "Nenhuma suíte encontrada para API."
          fi
      - name: Salvar resultados API
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: api-temp-${{ github.run_id }}
          path: ${{ env.RESULTS_DIR }}/api/**

  mobile:
    name: Mobile (fake)
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref != '' && inputs.ref || github.ref }}
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: pip
          cache-dependency-path: requirements.txt
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Executar testes Mobile (fake)
        run: |
          mkdir -p "${RESULTS_DIR}/mobile"
          if compgen -G "tests/mobile/*.robot" > /dev/null; then
            robot -d "${RESULTS_DIR}/mobile" -i mobile tests/mobile
          else
            echo "Nenhuma suíte encontrada para Mobile."
          fi
      - name: Salvar resultados Mobile
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mobile-temp-${{ github.run_id }}
          path: ${{ env.RESULTS_DIR }}/mobile/**

  resumo:
    name: Resumo & Artefatos Finais
    runs-on: ubuntu-latest
    needs: [api, mobile]
    if: always()
    steps:
      - name: Baixar artefatos temporários API
        uses: actions/download-artifact@v4
        with:
          name: api-temp-${{ github.run_id }}
          path: collected/api
        continue-on-error: true

      - name: Baixar artefatos temporários Mobile
        uses: actions/download-artifact@v4
        with:
          name: mobile-temp-${{ github.run_id }}
          path: collected/mobile
        continue-on-error: true

      - name: Upload API final
        uses: actions/upload-artifact@v4
        with:
          name: api-report
          path: collected/api/**
          if-no-files-found: warn

      - name: Upload Mobile final
        uses: actions/upload-artifact@v4
        with:
          name: mobile-report
          path: collected/mobile/**
          if-no-files-found: warn

      - name: Step Summary
        run: |
          echo "## Resumo do Pipeline" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Job | Resultado |" >> $GITHUB_STEP_SUMMARY
          echo "|---|---|" >> $GITHUB_STEP_SUMMARY
          echo "| API | ${{ needs.api.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Mobile | ${{ needs.mobile.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Artefatos finais: **api-report**, **mobile-report**" >> $GITHUB_STEP_SUMMARY
