name: CI — API & Mobile (Robot Framework)

on:
  pull_request:
    branches: ["**"]
  push:
    branches: ["main"]
  workflow_dispatch:
    inputs:
      ref:
        description: "Branch ou tag a executar (ex.: develop, feature/minha-branch)"
        required: false
        default: ""

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

env:
  PYTHON_VERSION: "3.11"
  RF_TAGS: ${{ github.event_name == 'pull_request' && 'smoke' || 'regression' }}

jobs:
  api:
    name: Testes de API
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref != '' && inputs.ref || github.ref }}
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: pip
          cache-dependency-path: requirements.txt
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Executar testes de API
        run: |
          mkdir -p API/Results
          PATHS=""
          if compgen -G "tests/api/*.robot" > /dev/null; then
            PATHS="${PATHS} tests/api"
          fi
          if compgen -G "tests/API_tests/*.robot" > /dev/null; then
            PATHS="${PATHS} tests/API_tests"
          fi
          if [ -n "${PATHS}" ]; then
            robot -d API/Results -i api ${PATHS}
          else
            echo "Nenhuma suíte encontrada para API."
          fi
      - name: Enviar Resultados dos Testes de API
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: api-test-results
          path: API/Results/**
          if-no-files-found: ignore
          retention-days: 5

  mobile:
    name: Testes Mobile (fake)
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref != '' && inputs.ref || github.ref }}
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: pip
          cache-dependency-path: requirements.txt
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Executar testes Mobile (fake)
        run: |
          mkdir -p Mobile/Results
          if compgen -G "tests/mobile/*.robot" > /dev/null; then
            robot -d Mobile/Results -i mobile tests/mobile
          else
            echo "Nenhuma suíte encontrada para Mobile."
          fi
      - name: Enviar Resultados dos Testes Mobile
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mobile-test-results
          path: Mobile/Results/**
          if-no-files-found: ignore
          retention-days: 5
